import React from 'react';
import { DiagramConfig } from '../../types';

interface DiagramProps {
  config: DiagramConfig;
  className?: string;
}

export const AcademicDiagram: React.FC<DiagramProps> = ({ config, className = '' }) => {
  const { title, caption, diagramKey, svgMarkup, imageUrl } = config;

  // Render Image directly if an image URL is supplied
  if (imageUrl) {
    return (
      <div className={`my-4 p-4 rounded-xl border border-slate-200 bg-white/95 text-center shadow-sm prevent-split ${className}`}>
        {title && <h5 className="text-xs font-bold uppercase tracking-wider text-slate-700 mb-2">{title}</h5>}
        <div className="flex justify-center items-center overflow-x-auto py-2">
          <img
            src={imageUrl}
            alt={title || 'Academic Diagram'}
            className="max-h-[300px] w-auto object-contain rounded-lg border border-slate-200 shadow-sm"
          />
        </div>
        {caption && <p className="text-[11px] text-slate-500 italic mt-2 text-center">{caption}</p>}
      </div>
    );
  }

  // Render raw SVG markup if custom SVG string was generated by AI
  if (svgMarkup) {
    return (
      <div className={`my-4 p-4 rounded-xl border border-slate-200 bg-white/95 text-center shadow-sm prevent-split ${className}`}>
        {title && <h5 className="text-xs font-bold uppercase tracking-wider text-slate-700 mb-2">{title}</h5>}
        <div
          className="flex justify-center items-center overflow-x-auto py-1"
          dangerouslySetInnerHTML={{ __html: svgMarkup }}
        />
        {caption && <p className="text-[11px] text-slate-500 italic mt-2 text-center">{caption}</p>}
      </div>
    );
  }

  // Determine the effective diagram key with smart content inspection
  const resolveEffectiveKey = (): string => {
    if (diagramKey && diagramKey !== 'custom' && diagramKey !== 'moraleProductivity') {
      return diagramKey;
    }

    const searchContext = `${title || ''} ${caption || ''}`.toLowerCase();

    if (
      searchContext.includes('hydro') ||
      searchContext.includes('water cycle') ||
      searchContext.includes('evaporation') ||
      searchContext.includes('precipitation') ||
      searchContext.includes('groundwater') ||
      searchContext.includes('runoff')
    ) {
      return 'hydrologicalCycle';
    }

    if (
      searchContext.includes('pipeline') ||
      searchContext.includes('hazard') ||
      searchContext.includes('reservation') ||
      searchContext.includes('throughput') ||
      searchContext.includes('stage')
    ) {
      return 'pipelineStages';
    }

    if (
      searchContext.includes('compiler') ||
      searchContext.includes('lexical') ||
      searchContext.includes('syntax') ||
      searchContext.includes('parser') ||
      searchContext.includes('ast') ||
      searchContext.includes('intermediate code')
    ) {
      return 'compilerPhases';
    }

    if (
      searchContext.includes('osi') ||
      searchContext.includes('network layer') ||
      searchContext.includes('tcp/ip') ||
      searchContext.includes('protocol stack')
    ) {
      return 'osiModel';
    }

    if (
      searchContext.includes('tree') ||
      searchContext.includes('binary search') ||
      searchContext.includes('bst') ||
      searchContext.includes('node')
    ) {
      return 'binaryTree';
    }

    if (
      searchContext.includes('photosynthesis') ||
      searchContext.includes('chloroplast') ||
      searchContext.includes('calvin')
    ) {
      return 'photosynthesis';
    }

    if (
      searchContext.includes('state transition') ||
      searchContext.includes('fsm') ||
      searchContext.includes('automata')
    ) {
      return 'stateTransition';
    }

    if (
      searchContext.includes('lookahead') ||
      searchContext.includes('look-ahead') ||
      searchContext.includes('cla')
    ) {
      return 'carryLookahead';
    }

    if (
      searchContext.includes('ripple carry') ||
      searchContext.includes('full adder')
    ) {
      return 'rippleCarryAdder';
    }

    if (
      searchContext.includes('von neumann') ||
      searchContext.includes('stored program')
    ) {
      return 'vonNeumann';
    }

    if (
      searchContext.includes('fetch') ||
      searchContext.includes('instruction cycle')
    ) {
      return 'fetchDecodeExecute';
    }

    if (
      searchContext.includes('feedback') ||
      searchContext.includes('closed loop') ||
      searchContext.includes('control system')
    ) {
      return 'systemFeedback';
    }

    if (
      searchContext.includes('floating point') ||
      searchContext.includes('ieee')
    ) {
      return 'ieee754';
    }

    if (
      searchContext.includes('graph') ||
      searchContext.includes('plot') ||
      searchContext.includes('parabola') ||
      searchContext.includes('curve')
    ) {
      return 'coordinateGraph';
    }

    if (
      searchContext.includes('memory') ||
      searchContext.includes('hierarchy') ||
      searchContext.includes('cache')
    ) {
      return 'memoryHierarchy';
    }

    if (
      searchContext.includes('morale') ||
      searchContext.includes('productivity')
    ) {
      return 'moraleProductivity';
    }

    return 'dynamicFlow';
  };

  const effectiveKey = resolveEffectiveKey();

  const renderDiagramGraphic = () => {
    switch (effectiveKey) {
      // ---------------------------------------------------------------------
      // 1. HYDROLOGICAL CYCLE (Water Cycle Schematic)
      // ---------------------------------------------------------------------
      case 'hydrologicalCycle':
      case 'waterCycle':
        return (
          <svg viewBox="0 0 680 320" className="w-full h-auto max-h-[300px] select-none" xmlns="http://www.w3.org/2000/svg">
            <defs>
              <linearGradient id="skyGrad" x1="0%" y1="0%" x2="0%" y2="100%">
                <stop offset="0%" stopColor="#BAE6FD" />
                <stop offset="60%" stopColor="#E0F2FE" />
                <stop offset="100%" stopColor="#F8FAFC" />
              </linearGradient>
              <linearGradient id="oceanGrad" x1="0%" y1="0%" x2="100%" y2="100%">
                <stop offset="0%" stopColor="#38BDF8" />
                <stop offset="100%" stopColor="#0284C7" />
              </linearGradient>
              <linearGradient id="mountainGrad" x1="0%" y1="0%" x2="0%" y2="100%">
                <stop offset="0%" stopColor="#64748B" />
                <stop offset="100%" stopColor="#334155" />
              </linearGradient>
              <linearGradient id="groundGrad" x1="0%" y1="0%" x2="0%" y2="100%">
                <stop offset="0%" stopColor="#86EFAC" />
                <stop offset="25%" stopColor="#15803D" />
                <stop offset="60%" stopColor="#78350F" />
                <stop offset="100%" stopColor="#451A03" />
              </linearGradient>
              <marker id="hydroArrowUp" viewBox="0 0 10 10" refX="6" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
                <path d="M 0 1 L 8 5 L 0 9 z" fill="#0284C7" />
              </marker>
              <marker id="hydroArrowRain" viewBox="0 0 10 10" refX="6" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
                <path d="M 0 1 L 8 5 L 0 9 z" fill="#2563EB" />
              </marker>
              <marker id="hydroArrowGround" viewBox="0 0 10 10" refX="6" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
                <path d="M 0 1 L 8 5 L 0 9 z" fill="#0369A1" />
              </marker>
            </defs>

            {/* Sky Background */}
            <rect x="20" y="20" width="640" height="280" rx="14" fill="url(#skyGrad)" stroke="#94A3B8" strokeWidth="1.5" />

            {/* Sun & Solar Radiation */}
            <circle cx="80" cy="70" r="28" fill="#FBBF24" stroke="#F59E0B" strokeWidth="2.5" />
            <g stroke="#F59E0B" strokeWidth="2" strokeLinecap="round">
              <line x1="80" y1="32" x2="80" y2="24" />
              <line x1="80" y1="108" x2="80" y2="116" />
              <line x1="42" y1="70" x2="34" y2="70" />
              <line x1="118" y1="70" x2="126" y2="70" />
              <line x1="53" y1="43" x2="47" y2="37" />
              <line x1="107" y1="97" x2="113" y2="103" />
              <line x1="53" y1="97" x2="47" y2="103" />
              <line x1="107" y1="43" x2="113" y2="37" />
            </g>
            <text x="80" y="74" textAnchor="middle" fill="#78350F" fontSize="10" fontWeight="bold">SUN</text>
            <text x="80" y="118" textAnchor="middle" fill="#B45309" fontSize="8" fontWeight="600">Solar Energy</text>

            {/* Mountains on Right Side */}
            <polygon points="420,220 520,90 600,220" fill="url(#mountainGrad)" />
            <polygon points="520,90 495,125 545,125" fill="#FFFFFF" opacity="0.9" /> {/* Snow Cap */}
            <polygon points="340,220 420,120 500,220" fill="#475569" />
            <polygon points="420,120 400,150 440,150" fill="#FFFFFF" opacity="0.8" />

            {/* Ground / Landscape Base */}
            <path d="M 200,220 Q 280,210 350,220 L 660,220 L 660,300 L 200,300 Z" fill="url(#groundGrad)" />

            {/* Ocean / Water Body on Left Side */}
            <path d="M 20,220 C 80,215 140,225 200,220 L 200,300 L 20,300 Z" fill="url(#oceanGrad)" />
            <text x="110" y="260" textAnchor="middle" fill="#FFFFFF" fontSize="13" fontWeight="bold">OCEAN / LAKE</text>
            <text x="110" y="275" textAnchor="middle" fill="#E0F2FE" fontSize="9">Water Storage Reservoir</text>

            {/* Clouds (Condensation) */}
            <g fill="#FFFFFF" stroke="#93C5FD" strokeWidth="1.5">
              <ellipse cx="280" cy="75" rx="35" ry="20" />
              <ellipse cx="310" cy="70" rx="28" ry="18" />
              <ellipse cx="255" cy="78" rx="24" ry="16" />
              <ellipse cx="480" cy="65" rx="42" ry="22" />
              <ellipse cx="515" cy="60" rx="30" ry="18" />
              <ellipse cx="450" cy="68" rx="26" ry="16" />
            </g>
            <text x="280" y="79" textAnchor="middle" fill="#1E3A8A" fontSize="10" fontWeight="bold">CONDENSATION</text>
            <text x="280" y="91" textAnchor="middle" fill="#3B82F6" fontSize="8">(Cloud Formation)</text>

            {/* 1. Evaporation Arrow (Ocean -> Sky) */}
            <path d="M 120,210 Q 140,140 180,105" fill="none" stroke="#0284C7" strokeWidth="2.5" strokeDasharray="5 3" markerEnd="url(#hydroArrowUp)" />
            <rect x="115" y="140" width="85" height="26" rx="6" fill="#F0F9FF" stroke="#0284C7" strokeWidth="1" />
            <text x="157" y="153" textAnchor="middle" fill="#0369A1" fontSize="9" fontWeight="bold">1. EVAPORATION</text>
            <text x="157" y="163" textAnchor="middle" fill="#0284C7" fontSize="8">Water Vapor Rises</text>

            {/* 2. Atmospheric Transport (Cloud Movement) */}
            <line x1="330" y1="65" x2="430" y2="65" stroke="#0284C7" strokeWidth="2" strokeDasharray="4 2" markerEnd="url(#hydroArrowUp)" />
            <text x="380" y="55" textAnchor="middle" fill="#0369A1" fontSize="8" fontWeight="bold">Atmospheric Transport</text>

            {/* 3. Transpiration from Trees */}
            <path d="M 330,210 Q 340,160 360,120" fill="none" stroke="#16A34A" strokeWidth="2" strokeDasharray="4 2" markerEnd="url(#hydroArrowUp)" />
            <text x="365" y="150" textAnchor="start" fill="#15803D" fontSize="8" fontWeight="bold">2. TRANSPIRATION</text>
            <text x="365" y="160" textAnchor="start" fill="#166534" fontSize="7.5">(From Vegetation)</text>

            {/* 4. Precipitation (Rainfall / Snow) */}
            <g stroke="#2563EB" strokeWidth="1.8" strokeLinecap="round">
              <line x1="460" y1="95" x2="455" y2="120" markerEnd="url(#hydroArrowRain)" />
              <line x1="485" y1="95" x2="480" y2="120" markerEnd="url(#hydroArrowRain)" />
              <line x1="510" y1="95" x2="505" y2="120" markerEnd="url(#hydroArrowRain)" />
            </g>
            <rect x="525" y="105" width="95" height="26" rx="6" fill="#EFF6FF" stroke="#2563EB" strokeWidth="1" />
            <text x="572" y="118" textAnchor="middle" fill="#1D4ED8" fontSize="9" fontWeight="bold">3. PRECIPITATION</text>
            <text x="572" y="128" textAnchor="middle" fill="#2563EB" fontSize="8">(Rain, Snow, Sleet)</text>

            {/* 5. Surface Runoff Arrow down mountain to ocean */}
            <path d="M 450,225 Q 320,235 210,235" fill="none" stroke="#0369A1" strokeWidth="3" markerEnd="url(#hydroArrowGround)" />
            <rect x="270" y="235" width="115" height="24" rx="5" fill="#FFFFFF" stroke="#0369A1" strokeWidth="1" />
            <text x="327" y="247" textAnchor="middle" fill="#0C4A6E" fontSize="8.5" fontWeight="bold">4. SURFACE RUNOFF</text>
            <text x="327" y="256" textAnchor="middle" fill="#0369A1" fontSize="7.5">Rivers flow to Ocean</text>

            {/* 6. Groundwater Infiltration / Percolation */}
            <path d="M 400,270 Q 300,285 205,275" fill="none" stroke="#78350F" strokeWidth="2.5" strokeDasharray="5 3" markerEnd="url(#hydroArrowGround)" />
            <text x="310" y="285" textAnchor="middle" fill="#FEF3C7" fontSize="8.5" fontWeight="bold">5. GROUNDWATER INFILTRATION / AQUIFER</text>
          </svg>
        );

      // ---------------------------------------------------------------------
      // 2. PIPELINE PROCESSOR (5-Stage RISC Pipelined Execution)
      // ---------------------------------------------------------------------
      case 'pipelineStages':
      case 'pipelineProcessor':
        return (
          <svg viewBox="0 0 680 230" className="w-full h-auto max-h-[230px] select-none" xmlns="http://www.w3.org/2000/svg">
            <defs>
              <marker id="pipeArr" viewBox="0 0 10 10" refX="6" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
                <path d="M 0 1 L 8 5 L 0 9 z" fill="#2563EB" />
              </marker>
              <linearGradient id="pipeStageGrad" x1="0%" y1="0%" x2="100%" y2="100%">
                <stop offset="0%" stopColor="#F8FAFC" />
                <stop offset="100%" stopColor="#EFF6FF" />
              </linearGradient>
            </defs>

            <rect x="15" y="15" width="650" height="200" rx="12" fill="#F8FAFC" stroke="#CBD5E1" strokeWidth="1.5" />
            <text x="340" y="38" textAnchor="middle" fill="#1E3A8A" fontSize="13" fontWeight="bold">
              5-STAGE INSTRUCTION PIPELINE ARCHITECTURE (RISC MODEL)
            </text>

            {[
              { code: 'IF', name: 'Instruction Fetch', desc: 'PC → Cache (MBR/IR)', color: '#3B82F6', bg: '#EFF6FF' },
              { code: 'ID', name: 'Instruction Decode', desc: 'Opcode Decode & Reg Read', color: '#10B981', bg: '#ECFDF5' },
              { code: 'EX', name: 'Execution', desc: 'ALU Op / Effective Addr', color: '#F59E0B', bg: '#FFFBEB' },
              { code: 'MEM', name: 'Memory Access', desc: 'Data Cache Load/Store', color: '#8B5CF6', bg: '#F5F3FF' },
              { code: 'WB', name: 'Write Back', desc: 'Result → Destination Reg', color: '#EC4899', bg: '#FDF2F8' },
            ].map((stage, idx) => {
              const x = 30 + idx * 125;
              return (
                <g key={stage.code}>
                  {/* Stage Box */}
                  <rect x={x} y="60" width="105" height="105" rx="10" fill={stage.bg} stroke={stage.color} strokeWidth="2" />
                  <circle cx={x + 52} cy="85" r="16" fill={stage.color} />
                  <text x={x + 52} y="90" textAnchor="middle" fill="#FFFFFF" fontSize="11" fontWeight="bold">{stage.code}</text>
                  <text x={x + 52} y="118" textAnchor="middle" fill="#1E293B" fontSize="9.5" fontWeight="bold">{stage.name}</text>
                  <text x={x + 52} y="135" textAnchor="middle" fill="#64748B" fontSize="8" width="90">{stage.desc}</text>

                  {/* Inter-stage Pipeline Register Bar */}
                  {idx < 4 && (
                    <>
                      <line x1={x + 105} y1="112" x2={x + 125} y2="112" stroke="#2563EB" strokeWidth="2.5" markerEnd="url(#pipeArr)" />
                      <rect x={x + 107} y="75" width="14" height="75" rx="3" fill="#334155" />
                      <text x={x + 114} y="116" textAnchor="middle" fill="#FFFFFF" fontSize="7" fontWeight="bold" transform={`rotate(-90 ${x + 114} 116)`}>REG</text>
                    </>
                  )}
                </g>
              );
            })}

            {/* Clock Synchronization Bus at Bottom */}
            <line x1="30" y1="190" x2="645" y2="190" stroke="#64748B" strokeWidth="1.5" strokeDasharray="4 2" />
            <text x="340" y="205" textAnchor="middle" fill="#475569" fontSize="10" fontWeight="600">
              Synchronous Master Clock Pulse (Latch Pipeline Registers every clock cycle τ)
            </text>
          </svg>
        );

      // ---------------------------------------------------------------------
      // 3. COMPILER PHASES (6-Phase Compiler Architecture)
      // ---------------------------------------------------------------------
      case 'compilerPhases':
        return (
          <svg viewBox="0 0 680 260" className="w-full h-auto max-h-[260px] select-none" xmlns="http://www.w3.org/2000/svg">
            <defs>
              <marker id="compArr" viewBox="0 0 10 10" refX="6" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
                <path d="M 0 1 L 8 5 L 0 9 z" fill="#4F46E5" />
              </marker>
            </defs>

            <rect x="15" y="15" width="650" height="230" rx="12" fill="#F8FAFC" stroke="#CBD5E1" strokeWidth="1.5" />
            <text x="340" y="36" textAnchor="middle" fill="#1E3A8A" fontSize="13" fontWeight="bold">
              THE 6 PHASES OF COMPILER ARCHITECTURE
            </text>

            {/* Front-End (Analysis) Box */}
            <rect x="25" y="55" width="300" height="130" rx="8" fill="#EEF2FF" stroke="#6366F1" strokeWidth="1.5" />
            <text x="175" y="75" textAnchor="middle" fill="#312E81" fontSize="11" fontWeight="bold">FRONT-END (ANALYSIS PHASE)</text>

            <rect x="35" y="90" width="85" height="40" rx="5" fill="#FFFFFF" stroke="#4F46E5" strokeWidth="1" />
            <text x="77" y="107" textAnchor="middle" fill="#1E1B4B" fontSize="8.5" fontWeight="bold">1. Lexical</text>
            <text x="77" y="120" textAnchor="middle" fill="#6366F1" fontSize="7.5">Token Stream</text>

            <line x1="120" y1="110" x2="135" y2="110" stroke="#4F46E5" strokeWidth="1.5" markerEnd="url(#compArr)" />

            <rect x="135" y="90" width="85" height="40" rx="5" fill="#FFFFFF" stroke="#4F46E5" strokeWidth="1" />
            <text x="177" y="107" textAnchor="middle" fill="#1E1B4B" fontSize="8.5" fontWeight="bold">2. Syntax</text>
            <text x="177" y="120" textAnchor="middle" fill="#6366F1" fontSize="7.5">Parse Tree</text>

            <line x1="220" y1="110" x2="235" y2="110" stroke="#4F46E5" strokeWidth="1.5" markerEnd="url(#compArr)" />

            <rect x="235" y="90" width="85" height="40" rx="5" fill="#FFFFFF" stroke="#4F46E5" strokeWidth="1" />
            <text x="277" y="107" textAnchor="middle" fill="#1E1B4B" fontSize="8.5" fontWeight="bold">3. Semantic</text>
            <text x="277" y="120" textAnchor="middle" fill="#6366F1" fontSize="7.5">Type Checked</text>

            {/* Back-End (Synthesis) Box */}
            <rect x="355" y="55" width="300" height="130" rx="8" fill="#ECFDF5" stroke="#10B981" strokeWidth="1.5" />
            <text x="505" y="75" textAnchor="middle" fill="#064E3B" fontSize="11" fontWeight="bold">BACK-END (SYNTHESIS PHASE)</text>

            <rect x="365" y="90" width="85" height="40" rx="5" fill="#FFFFFF" stroke="#10B981" strokeWidth="1" />
            <text x="407" y="107" textAnchor="middle" fill="#064E3B" fontSize="8.5" fontWeight="bold">4. ICG</text>
            <text x="407" y="120" textAnchor="middle" fill="#059669" fontSize="7.5">3-Address Code</text>

            <line x1="450" y1="110" x2="465" y2="110" stroke="#10B981" strokeWidth="1.5" markerEnd="url(#compArr)" />

            <rect x="465" y="90" width="85" height="40" rx="5" fill="#FFFFFF" stroke="#10B981" strokeWidth="1" />
            <text x="507" y="107" textAnchor="middle" fill="#064E3B" fontSize="8.5" fontWeight="bold">5. Optimizer</text>
            <text x="507" y="120" textAnchor="middle" fill="#059669" fontSize="7.5">Speed / Memory</text>

            <line x1="550" y1="110" x2="565" y2="110" stroke="#10B981" strokeWidth="1.5" markerEnd="url(#compArr)" />

            <rect x="565" y="90" width="85" height="40" rx="5" fill="#FFFFFF" stroke="#10B981" strokeWidth="1" />
            <text x="607" y="107" textAnchor="middle" fill="#064E3B" fontSize="8.5" fontWeight="bold">6. Code Gen</text>
            <text x="607" y="120" textAnchor="middle" fill="#059669" fontSize="7.5">Target Binary</text>

            {/* Connecting Front-End to Back-End */}
            <line x1="325" y1="110" x2="365" y2="110" stroke="#334155" strokeWidth="2.5" markerEnd="url(#compArr)" />

            {/* Central Symbol Table & Error Handler */}
            <rect x="130" y="195" width="200" height="36" rx="6" fill="#FEF3C7" stroke="#F59E0B" strokeWidth="1.5" />
            <text x="230" y="217" textAnchor="middle" fill="#78350F" fontSize="10" fontWeight="bold">SYMBOL TABLE MANAGEMENT</text>

            <rect x="350" y="195" width="200" height="36" rx="6" fill="#FEE2E2" stroke="#EF4444" strokeWidth="1.5" />
            <text x="450" y="217" textAnchor="middle" fill="#991B1B" fontSize="10" fontWeight="bold">ERROR DETECTION & REPORTING</text>
          </svg>
        );

      // ---------------------------------------------------------------------
      // 4. OSI 7-LAYER NETWORKING MODEL
      // ---------------------------------------------------------------------
      case 'osiModel':
        return (
          <svg viewBox="0 0 660 250" className="w-full h-auto max-h-[250px] select-none" xmlns="http://www.w3.org/2000/svg">
            <rect x="15" y="15" width="630" height="220" rx="12" fill="#F8FAFC" stroke="#CBD5E1" strokeWidth="1.5" />
            <text x="330" y="36" textAnchor="middle" fill="#1E3A8A" fontSize="13" fontWeight="bold">
              OSI 7-LAYER REFERENCE MODEL & PROTOCOLS
            </text>

            {[
              { num: 7, name: 'Application', pdu: 'Data', protos: 'HTTP, DNS, SSH, SMTP', color: '#DBEAFE', border: '#3B82F6' },
              { num: 6, name: 'Presentation', pdu: 'Data', protos: 'SSL/TLS, JPEG, ASCII, Compression', color: '#E0E7FF', border: '#6366F1' },
              { num: 5, name: 'Session', pdu: 'Data', protos: 'Sockets, RPC, NetBIOS, Sessions', color: '#EDE9FE', border: '#8B5CF6' },
              { num: 4, name: 'Transport', pdu: 'Segments', protos: 'TCP (Reliable), UDP (Fast), Port #', color: '#FAE8FF', border: '#D946EF' },
              { num: 3, name: 'Network', pdu: 'Packets', protos: 'IPv4, IPv6, ICMP, Routing, Routers', color: '#FEF3C7', border: '#F59E0B' },
              { num: 2, name: 'Data Link', pdu: 'Frames', protos: 'Ethernet, MAC Address, Switch, ARP', color: '#DCFCE7', border: '#22C55E' },
              { num: 1, name: 'Physical', pdu: 'Bits (0/1)', protos: 'Cables, Fiber, Radio Waves, Hubs', color: '#FEE2E2', border: '#EF4444' },
            ].map((layer, idx) => {
              const y = 50 + idx * 24;
              return (
                <g key={layer.num}>
                  <rect x="35" y={y} width="590" height="20" rx="4" fill={layer.color} stroke={layer.border} strokeWidth="1" />
                  <text x="50" y={y + 14} fill="#1E293B" fontSize="9" fontWeight="bold">Layer {layer.num}: {layer.name}</text>
                  <text x="240" y={y + 14} fill="#475569" fontSize="8.5" fontWeight="600">PDU: {layer.pdu}</text>
                  <text x="360" y={y + 14} fill="#334155" fontSize="8.5">Key Protocols: {layer.protos}</text>
                </g>
              );
            })}
          </svg>
        );

      // ---------------------------------------------------------------------
      // 5. BINARY TREE DATA STRUCTURE
      // ---------------------------------------------------------------------
      case 'binaryTree':
        return (
          <svg viewBox="0 0 540 220" className="w-full h-auto max-h-[220px] select-none" xmlns="http://www.w3.org/2000/svg">
            <rect x="15" y="15" width="510" height="190" rx="12" fill="#F8FAFC" stroke="#CBD5E1" strokeWidth="1.5" />
            <text x="270" y="36" textAnchor="middle" fill="#1E3A8A" fontSize="13" fontWeight="bold">
              HIERARCHICAL BINARY TREE DATA STRUCTURE
            </text>

            {/* Connecting Edges */}
            <line x1="270" y1="70" x2="160" y2="120" stroke="#64748B" strokeWidth="2" />
            <line x1="270" y1="70" x2="380" y2="120" stroke="#64748B" strokeWidth="2" />
            <line x1="160" y1="120" x2="100" y2="170" stroke="#64748B" strokeWidth="2" />
            <line x1="160" y1="120" x2="220" y2="170" stroke="#64748B" strokeWidth="2" />
            <line x1="380" y1="120" x2="440" y2="170" stroke="#64748B" strokeWidth="2" />

            {/* Root Node A */}
            <circle cx="270" cy="70" r="18" fill="#DBEAFE" stroke="#2563EB" strokeWidth="2" />
            <text x="270" y="75" textAnchor="middle" fill="#1E40AF" fontSize="12" fontWeight="bold">A</text>
            <text x="310" y="65" fill="#1E40AF" fontSize="9" fontWeight="bold">Root Node</text>

            {/* Level 1: Left Node B & Right Node C */}
            <circle cx="160" cy="120" r="16" fill="#DCFCE7" stroke="#16A34A" strokeWidth="2" />
            <text x="160" y="125" textAnchor="middle" fill="#14532D" fontSize="11" fontWeight="bold">B</text>

            <circle cx="380" cy="120" r="16" fill="#DCFCE7" stroke="#16A34A" strokeWidth="2" />
            <text x="380" y="125" textAnchor="middle" fill="#14532D" fontSize="11" fontWeight="bold">C</text>

            {/* Level 2: Leaves D, E, F */}
            <circle cx="100" cy="170" r="14" fill="#FEF3C7" stroke="#D97706" strokeWidth="1.5" />
            <text x="100" y="174" textAnchor="middle" fill="#78350F" fontSize="10" fontWeight="bold">D</text>

            <circle cx="220" cy="170" r="14" fill="#FEF3C7" stroke="#D97706" strokeWidth="1.5" />
            <text x="220" y="174" textAnchor="middle" fill="#78350F" fontSize="10" fontWeight="bold">E</text>

            <circle cx="440" cy="170" r="14" fill="#FEF3C7" stroke="#D97706" strokeWidth="1.5" />
            <text x="440" y="174" textAnchor="middle" fill="#78350F" fontSize="10" fontWeight="bold">F</text>
          </svg>
        );

      // ---------------------------------------------------------------------
      // 6. PHOTOSYNTHESIS (Biochemical Process Schematic)
      // ---------------------------------------------------------------------
      case 'photosynthesis':
        return (
          <svg viewBox="0 0 640 220" className="w-full h-auto max-h-[220px] select-none" xmlns="http://www.w3.org/2000/svg">
            <rect x="15" y="15" width="610" height="190" rx="12" fill="#F0FDF4" stroke="#86EFAC" strokeWidth="1.5" />
            <text x="320" y="38" textAnchor="middle" fill="#14532D" fontSize="13" fontWeight="bold">
              PHOTOSYNTHESIS BIOCHEMICAL ENERGY CONVERSION
            </text>

            {/* Inputs Box */}
            <rect x="35" y="60" width="140" height="100" rx="8" fill="#FFFFFF" stroke="#3B82F6" strokeWidth="1.5" />
            <text x="105" y="82" textAnchor="middle" fill="#1D4ED8" fontSize="11" fontWeight="bold">INPUTS</text>
            <text x="105" y="102" textAnchor="middle" fill="#334155" fontSize="9.5">• Sunlight (Photons)</text>
            <text x="105" y="120" textAnchor="middle" fill="#334155" fontSize="9.5">• 6 CO₂ (Carbon Dioxide)</text>
            <text x="105" y="138" textAnchor="middle" fill="#334155" fontSize="9.5">• 6 H₂O (Water)</text>

            <text x="200" y="115" textAnchor="middle" fill="#15803D" fontSize="22" fontWeight="bold">→</text>

            {/* Plant Chloroplast Engine */}
            <rect x="225" y="55" width="190" height="110" rx="12" fill="#DCFCE7" stroke="#16A34A" strokeWidth="2" />
            <text x="320" y="80" textAnchor="middle" fill="#14532D" fontSize="12" fontWeight="bold">CHLOROPLAST</text>
            <text x="320" y="100" textAnchor="middle" fill="#15803D" fontSize="9.5">1. Light Reactions (Thylakoids)</text>
            <text x="320" y="118" textAnchor="middle" fill="#15803D" fontSize="9.5">2. Calvin Cycle (Stroma)</text>
            <text x="320" y="142" textAnchor="middle" fill="#047857" fontSize="8.5" fontStyle="italic">Chlorophyll absorbs light</text>

            <text x="440" y="115" textAnchor="middle" fill="#15803D" fontSize="22" fontWeight="bold">→</text>

            {/* Outputs Box */}
            <rect x="465" y="60" width="140" height="100" rx="8" fill="#FFFFFF" stroke="#10B981" strokeWidth="1.5" />
            <text x="535" y="82" textAnchor="middle" fill="#047857" fontSize="11" fontWeight="bold">OUTPUTS</text>
            <text x="535" y="105" textAnchor="middle" fill="#334155" fontSize="10" fontWeight="bold">• Glucose (C₆H₁₂O₆)</text>
            <text x="535" y="128" textAnchor="middle" fill="#334155" fontSize="10" fontWeight="bold">• 6 O₂ (Oxygen Gas)</text>

            {/* Balanced Equation at bottom */}
            <text x="320" y="190" textAnchor="middle" fill="#166534" fontSize="10.5" fontWeight="bold">
              Balanced Equation: 6 CO₂ + 6 H₂O + Light Energy → C₆H₁₂O₆ + 6 O₂
            </text>
          </svg>
        );

      // ---------------------------------------------------------------------
      // 7. VON NEUMANN ARCHITECTURE
      // ---------------------------------------------------------------------
      case 'vonNeumann':
        return (
          <svg viewBox="0 0 650 320" className="w-full h-auto max-h-[300px] select-none" xmlns="http://www.w3.org/2000/svg">
            <defs>
              <linearGradient id="cpuGrad" x1="0%" y1="0%" x2="100%" y2="100%">
                <stop offset="0%" stopColor="#EBF4FF" />
                <stop offset="100%" stopColor="#D8EAFD" />
              </linearGradient>
              <linearGradient id="memGrad" x1="0%" y1="0%" x2="100%" y2="100%">
                <stop offset="0%" stopColor="#F0FDF4" />
                <stop offset="100%" stopColor="#DCFCE7" />
              </linearGradient>
              <linearGradient id="ioGrad" x1="0%" y1="0%" x2="100%" y2="100%">
                <stop offset="0%" stopColor="#FEF3C7" />
                <stop offset="100%" stopColor="#FDE68A" />
              </linearGradient>
              <marker id="arrowVN" viewBox="0 0 10 10" refX="6" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
                <path d="M 0 1 L 8 5 L 0 9 z" fill="#2563EB" />
              </marker>
            </defs>

            {/* Central Processing Unit (CPU) Box */}
            <rect x="30" y="30" width="280" height="240" rx="14" fill="url(#cpuGrad)" stroke="#2563EB" strokeWidth="2.5" />
            <text x="170" y="58" textAnchor="middle" fill="#1E3A8A" fontSize="14" fontWeight="bold">CENTRAL PROCESSING UNIT (CPU)</text>

            <rect x="50" y="75" width="240" height="48" rx="8" fill="#FFFFFF" stroke="#3B82F6" strokeWidth="1.5" />
            <text x="170" y="104" textAnchor="middle" fill="#1D4ED8" fontSize="12" fontWeight="600">Arithmetic & Logic Unit (ALU)</text>

            <rect x="50" y="133" width="240" height="48" rx="8" fill="#FFFFFF" stroke="#3B82F6" strokeWidth="1.5" />
            <text x="170" y="162" textAnchor="middle" fill="#1D4ED8" fontSize="12" fontWeight="600">Control Unit (CU)</text>

            <rect x="50" y="191" width="240" height="60" rx="8" fill="#FFFFFF" stroke="#3B82F6" strokeWidth="1.5" />
            <text x="170" y="212" textAnchor="middle" fill="#1E40AF" fontSize="11" fontWeight="700">Registers</text>
            <text x="170" y="235" textAnchor="middle" fill="#4B5563" fontSize="10">PC  •  MAR  •  MBR  •  IR  •  AC</text>

            {/* Memory Unit Box */}
            <rect x="420" y="30" width="200" height="150" rx="14" fill="url(#memGrad)" stroke="#16A34A" strokeWidth="2.5" />
            <text x="520" y="58" textAnchor="middle" fill="#14532D" fontSize="14" fontWeight="bold">MEMORY UNIT</text>

            <rect x="440" y="75" width="160" height="40" rx="6" fill="#FFFFFF" stroke="#22C55E" strokeWidth="1.5" />
            <text x="520" y="100" textAnchor="middle" fill="#15803D" fontSize="11" fontWeight="600">Stored Instructions (Code)</text>

            <rect x="440" y="125" width="160" height="40" rx="6" fill="#FFFFFF" stroke="#22C55E" strokeWidth="1.5" />
            <text x="520" y="150" textAnchor="middle" fill="#15803D" fontSize="11" fontWeight="600">Stored Data (Operands)</text>

            {/* I/O Unit Box */}
            <rect x="420" y="205" width="200" height="65" rx="14" fill="url(#ioGrad)" stroke="#D97706" strokeWidth="2" />
            <text x="520" y="232" textAnchor="middle" fill="#92400E" fontSize="13" fontWeight="bold">INPUT / OUTPUT SYSTEM</text>
            <text x="520" y="253" textAnchor="middle" fill="#B45309" fontSize="10">Keyboard, Display, Storage</text>

            {/* Bus Lines connecting CPU & Memory */}
            <line x1="310" y1="95" x2="420" y2="95" stroke="#2563EB" strokeWidth="2.5" markerEnd="url(#arrowVN)" markerStart="url(#arrowVN)" />
            <text x="365" y="85" textAnchor="middle" fill="#1E40AF" fontSize="9" fontWeight="700">Data Bus (Bidirectional)</text>

            <line x1="310" y1="145" x2="420" y2="145" stroke="#2563EB" strokeWidth="2.5" markerEnd="url(#arrowVN)" />
            <text x="365" y="135" textAnchor="middle" fill="#1E40AF" fontSize="9" fontWeight="700">Address Bus (CPU → Mem)</text>

            <line x1="310" y1="235" x2="420" y2="235" stroke="#D97706" strokeWidth="2" strokeDasharray="4 3" markerEnd="url(#arrowVN)" markerStart="url(#arrowVN)" />
            <text x="365" y="228" textAnchor="middle" fill="#B45309" fontSize="9" fontWeight="700">Control Bus</text>
          </svg>
        );

      // ---------------------------------------------------------------------
      // 8. FETCH-DECODE-EXECUTE CYCLE
      // ---------------------------------------------------------------------
      case 'fetchDecodeExecute':
        return (
          <svg viewBox="0 0 620 220" className="w-full h-auto max-h-[220px] select-none" xmlns="http://www.w3.org/2000/svg">
            <defs>
              <marker id="fdeArrowVN" viewBox="0 0 10 10" refX="6" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
                <path d="M 0 1 L 8 5 L 0 9 z" fill="#4F46E5" />
              </marker>
            </defs>

            {/* Step 1: FETCH */}
            <rect x="25" y="45" width="160" height="110" rx="14" fill="#EEF2FF" stroke="#6366F1" strokeWidth="2" />
            <circle cx="105" cy="72" r="16" fill="#4F46E5" />
            <text x="105" y="77" textAnchor="middle" fill="#FFFFFF" fontSize="13" fontWeight="bold">1</text>
            <text x="105" y="105" textAnchor="middle" fill="#312E81" fontSize="13" fontWeight="bold">FETCH</text>
            <text x="105" y="125" textAnchor="middle" fill="#4338CA" fontSize="9.5">Read Instruction from</text>
            <text x="105" y="139" textAnchor="middle" fill="#4338CA" fontSize="9.5">Memory at address PC</text>

            {/* Arrow 1 to 2 */}
            <line x1="185" y1="100" x2="230" y2="100" stroke="#4F46E5" strokeWidth="2.5" markerEnd="url(#fdeArrowVN)" />

            {/* Step 2: DECODE */}
            <rect x="230" y="45" width="160" height="110" rx="14" fill="#F0FDF4" stroke="#22C55E" strokeWidth="2" />
            <circle cx="310" cy="72" r="16" fill="#16A34A" />
            <text x="310" y="77" textAnchor="middle" fill="#FFFFFF" fontSize="13" fontWeight="bold">2</text>
            <text x="310" y="105" textAnchor="middle" fill="#14532D" fontSize="13" fontWeight="bold">DECODE</text>
            <text x="310" y="125" textAnchor="middle" fill="#15803D" fontSize="9.5">Control Unit decodes</text>
            <text x="310" y="139" textAnchor="middle" fill="#15803D" fontSize="9.5">Opcode & Addressing Mode</text>

            {/* Arrow 2 to 3 */}
            <line x1="390" y1="100" x2="435" y2="100" stroke="#4F46E5" strokeWidth="2.5" markerEnd="url(#fdeArrowVN)" />

            {/* Step 3: EXECUTE */}
            <rect x="435" y="45" width="160" height="110" rx="14" fill="#FFF7ED" stroke="#F97316" strokeWidth="2" />
            <circle cx="515" cy="72" r="16" fill="#EA580C" />
            <text x="515" y="77" textAnchor="middle" fill="#FFFFFF" fontSize="13" fontWeight="bold">3</text>
            <text x="515" y="105" textAnchor="middle" fill="#7C2D12" fontSize="13" fontWeight="bold">EXECUTE</text>
            <text x="515" y="125" textAnchor="middle" fill="#C2410C" fontSize="9.5">ALU performs operation</text>
            <text x="515" y="139" textAnchor="middle" fill="#C2410C" fontSize="9.5">Store result, update PC</text>

            {/* Loopback Arrow */}
            <path d="M 515 155 Q 515 195 310 195 T 105 155" fill="none" stroke="#6366F1" strokeWidth="2" strokeDasharray="5 3" markerEnd="url(#fdeArrowVN)" />
            <text x="310" y="185" textAnchor="middle" fill="#4F46E5" fontSize="10" fontWeight="600">Next Instruction Cycle (PC = PC + 1)</text>
          </svg>
        );

      // ---------------------------------------------------------------------
      // 9. SYSTEM FEEDBACK (Control Systems)
      // ---------------------------------------------------------------------
      case 'systemFeedback':
        return (
          <svg viewBox="0 0 640 230" className="w-full h-auto max-h-[230px] select-none" xmlns="http://www.w3.org/2000/svg">
            <defs>
              <marker id="sysArrVN" viewBox="0 0 10 10" refX="6" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
                <path d="M 0 1 L 8 5 L 0 9 z" fill="#0284C7" />
              </marker>
            </defs>

            <line x1="20" y1="75" x2="80" y2="75" stroke="#0284C7" strokeWidth="2.5" markerEnd="url(#sysArrVN)" />
            <text x="45" y="62" textAnchor="middle" fill="#0369A1" fontSize="11" fontWeight="700">Input r(t)</text>

            <circle cx="95" cy="75" r="15" fill="#E0F2FE" stroke="#0284C7" strokeWidth="2" />
            <text x="95" y="79" textAnchor="middle" fill="#0369A1" fontSize="14" fontWeight="bold">∑</text>
            <text x="82" y="70" textAnchor="middle" fill="#15803D" fontSize="10" fontWeight="bold">+</text>
            <text x="95" y="102" textAnchor="middle" fill="#B91C1C" fontSize="12" fontWeight="bold">−</text>

            <line x1="110" y1="75" x2="160" y2="75" stroke="#0284C7" strokeWidth="2" markerEnd="url(#sysArrVN)" />
            <text x="135" y="62" textAnchor="middle" fill="#0369A1" fontSize="10" fontWeight="600">e(t)</text>

            <rect x="160" y="45" width="120" height="60" rx="10" fill="#F0F9FF" stroke="#0284C7" strokeWidth="2" />
            <text x="220" y="72" textAnchor="middle" fill="#0C4A6E" fontSize="12" fontWeight="bold">Controller</text>
            <text x="220" y="90" textAnchor="middle" fill="#0284C7" fontSize="10">G₁(s)</text>

            <line x1="280" y1="75" x2="330" y2="75" stroke="#0284C7" strokeWidth="2" markerEnd="url(#sysArrVN)" />
            <text x="305" y="62" textAnchor="middle" fill="#0369A1" fontSize="10" fontWeight="600">u(t)</text>

            <rect x="330" y="45" width="130" height="60" rx="10" fill="#ECFDF5" stroke="#10B981" strokeWidth="2" />
            <text x="395" y="72" textAnchor="middle" fill="#064E3B" fontSize="12" fontWeight="bold">Plant / Process</text>
            <text x="395" y="90" textAnchor="middle" fill="#059669" fontSize="10">G₂(s)</text>

            <line x1="460" y1="75" x2="580" y2="75" stroke="#0284C7" strokeWidth="2.5" markerEnd="url(#sysArrVN)" />
            <circle cx="510" cy="75" r="4" fill="#0284C7" />
            <text x="560" y="62" textAnchor="middle" fill="#0369A1" fontSize="11" fontWeight="700">Output c(t)</text>

            <line x1="510" y1="75" x2="510" y2="165" stroke="#0284C7" strokeWidth="2" />
            <line x1="510" y1="165" x2="430" y2="165" stroke="#0284C7" strokeWidth="2" markerEnd="url(#sysArrVN)" />

            <rect x="270" y="135" width="160" height="60" rx="10" fill="#FEF3C7" stroke="#F59E0B" strokeWidth="2" />
            <text x="350" y="162" textAnchor="middle" fill="#78350F" fontSize="12" fontWeight="bold">Feedback Sensor / Element</text>
            <text x="350" y="180" textAnchor="middle" fill="#B45309" fontSize="10">H(s)</text>

            <line x1="270" y1="165" x2="95" y2="165" stroke="#0284C7" strokeWidth="2" />
            <line x1="95" y1="165" x2="95" y2="90" stroke="#0284C7" strokeWidth="2" markerEnd="url(#sysArrVN)" />
            <text x="180" y="155" textAnchor="middle" fill="#0369A1" fontSize="10">Feedback signal b(t)</text>
          </svg>
        );

      // ---------------------------------------------------------------------
      // 10. RIPPLE CARRY ADDER
      // ---------------------------------------------------------------------
      case 'rippleCarryAdder':
        return (
          <svg viewBox="0 0 620 180" className="w-full h-auto max-h-[180px] select-none" xmlns="http://www.w3.org/2000/svg">
            <defs>
              <marker id="rcArrVN" viewBox="0 0 10 10" refX="6" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
                <path d="M 0 1 L 8 5 L 0 9 z" fill="#DC2626" />
              </marker>
              <marker id="sumArrVN" viewBox="0 0 10 10" refX="6" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
                <path d="M 0 1 L 8 5 L 0 9 z" fill="#2563EB" />
              </marker>
            </defs>

            {[3, 2, 1, 0].map((idx, col) => {
              const x = 35 + col * 140;
              return (
                <g key={idx}>
                  <rect x={x} y="40" width="105" height="85" rx="8" fill="#F8FAFC" stroke="#334155" strokeWidth="2" />
                  <text x={x + 52} y="72" textAnchor="middle" fill="#0F172A" fontSize="13" fontWeight="bold">FA {idx}</text>
                  <text x={x + 52} y="92" textAnchor="middle" fill="#64748B" fontSize="9">Full Adder</text>

                  <line x1={x + 30} y1="10" x2={x + 30} y2="40" stroke="#2563EB" strokeWidth="2" markerEnd="url(#sumArrVN)" />
                  <text x={x + 30} y="8" textAnchor="middle" fill="#1D4ED8" fontSize="10" fontWeight="bold">A{idx}</text>

                  <line x1={x + 75} y1="10" x2={x + 75} y2="40" stroke="#2563EB" strokeWidth="2" markerEnd="url(#sumArrVN)" />
                  <text x={x + 75} y="8" textAnchor="middle" fill="#1D4ED8" fontSize="10" fontWeight="bold">B{idx}</text>

                  <line x1={x + 52} y1="125" x2={x + 52} y2="155" stroke="#2563EB" strokeWidth="2" markerEnd="url(#sumArrVN)" />
                  <text x={x + 52} y="170" textAnchor="middle" fill="#1D4ED8" fontSize="11" fontWeight="bold">S{idx}</text>

                  {col < 3 ? (
                    <>
                      <line x1={x + 140} y1="80" x2={x + 105} y2="80" stroke="#DC2626" strokeWidth="2" markerEnd="url(#rcArrVN)" />
                      <text x={x + 122} y="72" textAnchor="middle" fill="#B91C1C" fontSize="9" fontWeight="bold">C{idx}</text>
                    </>
                  ) : (
                    <>
                      <line x1={x + 135} y1="80" x2={x + 105} y2="80" stroke="#DC2626" strokeWidth="2" markerEnd="url(#rcArrVN)" />
                      <text x={x + 130} y="72" textAnchor="middle" fill="#B91C1C" fontSize="10" fontWeight="bold">C₀ (Cin)</text>
                    </>
                  )}
                </g>
              );
            })}

            <line x1="35" y1="80" x2="5" y2="80" stroke="#DC2626" strokeWidth="2.5" markerEnd="url(#rcArrVN)" />
            <text x="18" y="70" textAnchor="middle" fill="#B91C1C" fontSize="11" fontWeight="bold">C₄ (Cout)</text>
          </svg>
        );

      // ---------------------------------------------------------------------
      // 11. CARRY LOOK-AHEAD LOGIC
      // ---------------------------------------------------------------------
      case 'carryLookahead':
        return (
          <svg viewBox="0 0 620 200" className="w-full h-auto max-h-[200px] select-none" xmlns="http://www.w3.org/2000/svg">
            <rect x="15" y="15" width="590" height="170" rx="12" fill="#F8FAFC" stroke="#CBD5E1" strokeWidth="1.5" />
            <text x="310" y="38" textAnchor="middle" fill="#1E3A8A" fontSize="13" fontWeight="bold">
              CARRY LOOK-AHEAD (CLA) PARALLEL LOGIC GENERATOR
            </text>

            <rect x="40" y="60" width="160" height="100" rx="8" fill="#EFF6FF" stroke="#3B82F6" strokeWidth="1.5" />
            <text x="120" y="85" textAnchor="middle" fill="#1D4ED8" fontSize="11" fontWeight="bold">GENERATE (G)</text>
            <text x="120" y="105" textAnchor="middle" fill="#1E40AF" fontSize="11">Gᵢ = Aᵢ · Bᵢ</text>
            <text x="120" y="130" textAnchor="middle" fill="#64748B" fontSize="9">Bit Carry Generation</text>

            <rect x="230" y="60" width="160" height="100" rx="8" fill="#ECFDF5" stroke="#10B981" strokeWidth="1.5" />
            <text x="310" y="85" textAnchor="middle" fill="#064E3B" fontSize="11" fontWeight="bold">PROPAGATE (P)</text>
            <text x="310" y="105" textAnchor="middle" fill="#047857" fontSize="11">Pᵢ = Aᵢ ⊕ Bᵢ</text>
            <text x="310" y="130" textAnchor="middle" fill="#64748B" fontSize="9">Bit Carry Propagation</text>

            <rect x="420" y="60" width="160" height="100" rx="8" fill="#FEF3C7" stroke="#F59E0B" strokeWidth="1.5" />
            <text x="500" y="85" textAnchor="middle" fill="#78350F" fontSize="11" fontWeight="bold">LOOKAHEAD CARRY</text>
            <text x="500" y="105" textAnchor="middle" fill="#92400E" fontSize="10">Cᵢ₊₁ = Gᵢ + Pᵢ · Cᵢ</text>
            <text x="500" y="130" textAnchor="middle" fill="#64748B" fontSize="9">Instant Parallel Calculation</text>
          </svg>
        );

      // ---------------------------------------------------------------------
      // 12. IEEE-754 32-BIT FLOATING POINT FORMAT
      // ---------------------------------------------------------------------
      case 'ieee754':
        return (
          <svg viewBox="0 0 620 160" className="w-full h-auto max-h-[160px] select-none" xmlns="http://www.w3.org/2000/svg">
            <text x="310" y="24" textAnchor="middle" fill="#1E293B" fontSize="13" fontWeight="bold">
              IEEE-754 Single Precision 32-bit Floating Point Format
            </text>

            <rect x="30" y="42" width="560" height="46" rx="6" fill="#F1F5F9" stroke="#94A3B8" strokeWidth="1.5" />

            <rect x="30" y="42" width="60" height="46" rx="4" fill="#FEE2E2" stroke="#EF4444" strokeWidth="1.5" />
            <text x="60" y="65" textAnchor="middle" fill="#991B1B" fontSize="12" fontWeight="bold">Sign (S)</text>
            <text x="60" y="78" textAnchor="middle" fill="#B91C1C" fontSize="9">1 Bit (Bit 31)</text>

            <rect x="90" y="42" width="170" height="46" fill="#FEF3C7" stroke="#F59E0B" strokeWidth="1.5" />
            <text x="175" y="65" textAnchor="middle" fill="#92400E" fontSize="12" fontWeight="bold">Biased Exponent (E)</text>
            <text x="175" y="78" textAnchor="middle" fill="#B45309" fontSize="9">8 Bits (Bits 30–23) • Bias = 127</text>

            <rect x="260" y="42" width="330" height="46" rx="4" fill="#E0F2FE" stroke="#0284C7" strokeWidth="1.5" />
            <text x="425" y="65" textAnchor="middle" fill="#075985" fontSize="12" fontWeight="bold">Fraction / Mantissa (M)</text>
            <text x="425" y="78" textAnchor="middle" fill="#0369A1" fontSize="9">23 Bits (Bits 22–0) • Hidden 1.M</text>

            <text x="310" y="122" textAnchor="middle" fill="#334155" fontSize="12" fontWeight="600">
              Value = (-1)ˢ × (1.M) × 2^(E - 127)
            </text>
          </svg>
        );

      // ---------------------------------------------------------------------
      // 13. MEMORY HIERARCHY PYRAMID
      // ---------------------------------------------------------------------
      case 'memoryHierarchy':
        return (
          <svg viewBox="0 0 540 210" className="w-full h-auto max-h-[210px] select-none" xmlns="http://www.w3.org/2000/svg">
            <polygon points="270,25 210,65 330,65" fill="#DBEAFE" stroke="#3B82F6" strokeWidth="1.5" />
            <text x="270" y="52" textAnchor="middle" fill="#1E40AF" fontSize="10" fontWeight="bold">Registers (&lt;1 KB)</text>

            <polygon points="210,68 330,68 360,105 180,105" fill="#E0E7FF" stroke="#6366F1" strokeWidth="1.5" />
            <text x="270" y="90" textAnchor="middle" fill="#3730A3" fontSize="10" fontWeight="bold">Cache (L1, L2, L3) [KB–MB]</text>

            <polygon points="180,108 360,108 400,145 140,145" fill="#DCFCE7" stroke="#22C55E" strokeWidth="1.5" />
            <text x="270" y="130" textAnchor="middle" fill="#166534" fontSize="10" fontWeight="bold">Main Memory (RAM) [8GB–64GB]</text>

            <polygon points="140,148 400,148 450,190 90,190" fill="#FEF3C7" stroke="#F59E0B" strokeWidth="1.5" />
            <text x="270" y="173" textAnchor="middle" fill="#92400E" fontSize="10" fontWeight="bold">Secondary Storage (SSD / HDD / Cloud) [TB]</text>

            <text x="45" y="70" fill="#DC2626" fontSize="9" fontWeight="bold">▲ Speed & Cost</text>
            <text x="440" y="160" fill="#059669" fontSize="9" fontWeight="bold">▼ Capacity</text>
          </svg>
        );

      // ---------------------------------------------------------------------
      // 14. COORDINATE GRAPH (y = x²)
      // ---------------------------------------------------------------------
      case 'coordinateGraph':
        return (
          <svg viewBox="0 0 500 200" className="w-full h-auto max-h-[200px] select-none" xmlns="http://www.w3.org/2000/svg">
            <defs>
              <pattern id="gridPattern" width="20" height="20" patternUnits="userSpaceOnUse">
                <path d="M 20 0 L 0 0 0 20" fill="none" stroke="#F1F5F9" strokeWidth="1" />
              </pattern>
            </defs>
            <rect x="50" y="20" width="400" height="150" fill="url(#gridPattern)" />

            <line x1="50" y1="160" x2="450" y2="160" stroke="#475569" strokeWidth="2" />
            <text x="460" y="165" fill="#334155" fontSize="11" fontWeight="bold">x</text>

            <line x1="250" y1="170" x2="250" y2="20" stroke="#475569" strokeWidth="2" />
            <text x="250" y="15" textAnchor="middle" fill="#334155" fontSize="11" fontWeight="bold">y</text>

            <path d="M 130 30 Q 250 160 370 30" fill="none" stroke="#2563EB" strokeWidth="3" />
            <circle cx="250" cy="160" r="4" fill="#DC2626" />
            <text x="250" y="178" textAnchor="middle" fill="#991B1B" fontSize="10">Origin (0,0)</text>

            <rect x="330" y="45" width="90" height="28" rx="6" fill="#EFF6FF" stroke="#3B82F6" strokeWidth="1" />
            <text x="375" y="63" textAnchor="middle" fill="#1E40AF" fontSize="11" fontWeight="bold">y = x²</text>
          </svg>
        );

      // ---------------------------------------------------------------------
      // 15. MORALE & PRODUCTIVITY (Specific HR / Organizational Model)
      // ---------------------------------------------------------------------
      case 'moraleProductivity':
        return (
          <svg viewBox="0 0 600 200" className="w-full h-auto max-h-[200px] select-none" xmlns="http://www.w3.org/2000/svg">
            <rect x="20" y="25" width="560" height="155" rx="12" fill="#F8FAFC" stroke="#CBD5E1" strokeWidth="1.5" />
            
            <rect x="45" y="45" width="140" height="110" rx="8" fill="#EEF2FF" stroke="#6366F1" strokeWidth="1.5" />
            <text x="115" y="70" textAnchor="middle" fill="#312E81" fontSize="12" fontWeight="bold">HIGH MORALE</text>
            <text x="115" y="90" textAnchor="middle" fill="#4338CA" fontSize="9">• Confidence & Trust</text>
            <text x="115" y="105" textAnchor="middle" fill="#4338CA" fontSize="9">• Work Satisfaction</text>
            <text x="115" y="120" textAnchor="middle" fill="#4338CA" fontSize="9">• Recognition</text>
            <text x="115" y="135" textAnchor="middle" fill="#4338CA" fontSize="9">• Low Absenteeism</text>

            <circle cx="215" cy="100" r="14" fill="#E2E8F0" />
            <text x="215" y="105" textAnchor="middle" fill="#334155" fontSize="16" fontWeight="bold">+</text>

            <rect x="245" y="45" width="140" height="110" rx="8" fill="#ECFDF5" stroke="#10B981" strokeWidth="1.5" />
            <text x="315" y="70" textAnchor="middle" fill="#064E3B" fontSize="12" fontWeight="bold">ENABLERS</text>
            <text x="315" y="90" textAnchor="middle" fill="#047857" fontSize="9">• Training & Tools</text>
            <text x="315" y="105" textAnchor="middle" fill="#047857" fontSize="9">• Fair Compensation</text>
            <text x="315" y="120" textAnchor="middle" fill="#047857" fontSize="9">• Clear Direction</text>
            <text x="315" y="135" textAnchor="middle" fill="#047857" fontSize="9">• Healthy Workspace</text>

            <text x="405" y="106" textAnchor="middle" fill="#0284C7" fontSize="20" fontWeight="bold">→</text>

            <rect x="425" y="45" width="135" height="110" rx="8" fill="#FEF3C7" stroke="#F59E0B" strokeWidth="1.5" />
            <text x="492" y="70" textAnchor="middle" fill="#78350F" fontSize="12" fontWeight="bold">PRODUCTIVITY</text>
            <text x="492" y="90" textAnchor="middle" fill="#B45309" fontSize="9">• High Output Quality</text>
            <text x="492" y="105" textAnchor="middle" fill="#B45309" fontSize="9">• Reduced Waste</text>
            <text x="492" y="120" textAnchor="middle" fill="#B45309" fontSize="9">• Faster Innovation</text>
            <text x="492" y="135" textAnchor="middle" fill="#B45309" fontSize="9">• Long-term Growth</text>
          </svg>
        );

      // ---------------------------------------------------------------------
      // 16. DYNAMIC PROCESS FLOWCHART (Smart Universal Academic Fallback)
      // ---------------------------------------------------------------------
      case 'dynamicFlow':
      default: {
        const diagramHeadline = (title || 'Conceptual Architecture Flowchart').replace(/^figure:?\s*/i, '');
        return (
          <svg viewBox="0 0 650 200" className="w-full h-auto max-h-[200px] select-none" xmlns="http://www.w3.org/2000/svg">
            <defs>
              <marker id="dynArr" viewBox="0 0 10 10" refX="6" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
                <path d="M 0 1 L 8 5 L 0 9 z" fill="#2563EB" />
              </marker>
            </defs>

            <rect x="15" y="15" width="620" height="170" rx="12" fill="#F8FAFC" stroke="#CBD5E1" strokeWidth="1.5" />
            <text x="325" y="38" textAnchor="middle" fill="#1E3A8A" fontSize="12" fontWeight="bold">
              {diagramHeadline.toUpperCase()}
            </text>

            {/* Stage 1: Input & Parameters */}
            <rect x="35" y="55" width="165" height="95" rx="8" fill="#EFF6FF" stroke="#3B82F6" strokeWidth="1.5" />
            <circle cx="60" cy="78" r="12" fill="#3B82F6" />
            <text x="60" y="82" textAnchor="middle" fill="#FFFFFF" fontSize="10" fontWeight="bold">1</text>
            <text x="120" y="82" textAnchor="middle" fill="#1E40AF" fontSize="10.5" fontWeight="bold">Input & Parameters</text>
            <text x="117" y="105" textAnchor="middle" fill="#475569" fontSize="8.5">• Initial Conditions</text>
            <text x="117" y="120" textAnchor="middle" fill="#475569" fontSize="8.5">• Raw Data / Signals</text>

            <line x1="200" y1="102" x2="235" y2="102" stroke="#2563EB" strokeWidth="2.5" markerEnd="url(#dynArr)" />

            {/* Stage 2: Processing & Functional Logic */}
            <rect x="235" y="55" width="180" height="95" rx="8" fill="#ECFDF5" stroke="#10B981" strokeWidth="1.5" />
            <circle cx="260" cy="78" r="12" fill="#10B981" />
            <text x="260" y="82" textAnchor="middle" fill="#FFFFFF" fontSize="10" fontWeight="bold">2</text>
            <text x="330" y="82" textAnchor="middle" fill="#064E3B" fontSize="10.5" fontWeight="bold">Processing Engine</text>
            <text x="325" y="105" textAnchor="middle" fill="#475569" fontSize="8.5">• Core Transformations</text>
            <text x="325" y="120" textAnchor="middle" fill="#475569" fontSize="8.5">• Rule Evaluation / Logic</text>

            <line x1="415" y1="102" x2="450" y2="102" stroke="#2563EB" strokeWidth="2.5" markerEnd="url(#dynArr)" />

            {/* Stage 3: Output & Verification */}
            <rect x="450" y="55" width="165" height="95" rx="8" fill="#FEF3C7" stroke="#F59E0B" strokeWidth="1.5" />
            <circle cx="475" cy="78" r="12" fill="#F59E0B" />
            <text x="475" y="82" textAnchor="middle" fill="#FFFFFF" fontSize="10" fontWeight="bold">3</text>
            <text x="535" y="82" textAnchor="middle" fill="#78350F" fontSize="10.5" fontWeight="bold">Output & Results</text>
            <text x="532" y="105" textAnchor="middle" fill="#475569" fontSize="8.5">• Validated Solution</text>
            <text x="532" y="120" textAnchor="middle" fill="#475569" fontSize="8.5">• Target System State</text>

            {/* Feedback / Cycle Return Line */}
            <path d="M 532 150 Q 325 175 117 150" fill="none" stroke="#94A3B8" strokeWidth="1.5" strokeDasharray="4 2" markerEnd="url(#dynArr)" />
            <text x="325" y="168" textAnchor="middle" fill="#64748B" fontSize="8" fontWeight="600">Verification & Feedback Loop</text>
          </svg>
        );
      }
    }
  };

  return (
    <div className={`my-4 p-4 rounded-xl border border-slate-200 bg-white/95 text-center shadow-sm prevent-split ${className}`}>
      {title && <h5 className="text-xs font-bold uppercase tracking-wider text-slate-700 mb-2">{title}</h5>}
      <div className="flex justify-center items-center overflow-x-auto py-1">
        {renderDiagramGraphic()}
      </div>
      {caption && <p className="text-[11px] text-slate-500 italic mt-2 text-center">{caption}</p>}
    </div>
  );
};
